### PR TITLE
Untitled

### PR DESCRIPTION
**Pull request by Paxa**
Fixed double initialazing

### CODE REVIEW

**Comment by cheeaun** [comment]
Hey thanks for the pull request. I've applied some of your fixes and not pulling this one because the files changed seems kinda weird especially the CSS files.

**Comment by Paxa** [comment]
Thank you.
Think this is weird end of line in files, I don't know why my mac os and git 1.7 did it

**Comment by cheeaun** [comment]
I guess you could try using 'git gui' whenever committing, so that you can see what are the actual changes in it. It's kinda messy (for me) to apply pull requests when the changed files don't make sense :)

**Comment by Paxa** [comment]
Thank you for advise, I'll use it :) git gui is awesome, may be even more then gitx

**Comment by cheeaun** [comment]
Oh, if you're using gitx, try out this fork http://github.com/brotherbard/gitx . It has the same functionality like git gui, but with nicer UI :)

**Pull request closed without merging**
